In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

array_3d = np.array([[[1,2],[3,4]], [[5,6],[7,8]]])

print(array_3d[1,1,0])


7


In [ ]:
import numpy as np

# Crear un array con 20 dimensiones, cada dimensión tiene tamaño 1
array_5d = np.eye(5)
print(array_5d)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
import numpy as np
#crea la digonal con los datos que deseamos
diag = np.diag([0,1,2,3,4,5])
print(diag) # imprime la diagonal



[[0 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 2 0 0 0]
 [0 0 0 3 0 0]
 [0 0 0 0 4 0]
 [0 0 0 0 0 5]]


In [ ]:
#crear un array 3 dimencional con 5 indices, 3 columnas y 4 filas
import numpy as np
array_5d = np.random.random((5,3,4))
print(array_5d)
print(array_5d.ndim) # indica las dimenciones del array
print(array_5d.shape) # indica cuantas filas columnas e indices tien el array
print(array_5d.dtype) # indica el tipo de dato del array





3
(5, 3, 4)
float64


In [ ]:
#operaciones estadisticas y matematicas

array =  np.array([[1,2,3,4],[5,6,7,8]])
print(array)

maximo = np.max(array)
print(maximo)

minimo = np.min(array)
print(minimo)

suma = np.sum(array)
print(suma)

median= np.median(array)
print(median)

desviacion = np.std(array)
print(desviacion)




[[1 2 3 4]
 [5 6 7 8]]
8
1
36
4.5
2.29128784747792


In [ ]:
import numpy as np
A= np.array([[1,2],[3,4]])
B= np.array([[5,6],[7,8]])
suma= A+B
print(suma)
resta= A-B
print(resta)
division= A/B
print(division)
multiplicacion= np.dot(A,B)
print(multiplicacion)


[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[19 22]
 [43 50]]
Valores propios de A:
 [-0.37228132  5.37228132]
Vectores propios de A:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [ ]:
import numpy as np

# Crear un array tridimensional aleatorio
array = np.random.randint(1, 10, size=(4, 3, 3))
print("Array tridimensional:")
print(array)

lista = []
i = 0

# Iterar sobre el primer eje de la matriz
while i < 4:
    # Seleccionar el subarray en la posición i
    subarray = array[i]

    # Filtrar los valores mayores o iguales a 5 y agregarlos a la lista
    elementos_filtrados = subarray[subarray >= 5]  # Esto selecciona solo los elementos >= 5
    lista.append(elementos_filtrados.tolist()) # Convertir a lista y añadir a la lista principal


    i += 1

print("\nLista de elementos mayores o iguales a 5:")
print(lista)


Array tridimensional:
[[[3 7 1]
  [8 7 5]
  [7 6 6]]

 [[3 7 8]
  [2 3 6]
  [8 9 6]]

 [[1 4 1]
  [6 2 7]
  [7 3 8]]

 [[8 3 6]
  [6 1 1]
  [3 5 7]]]

Lista de elementos mayores o iguales a 5:
[[7, 8, 7, 5, 7, 6, 6], [7, 8, 6, 8, 9, 6], [6, 7, 7, 8], [8, 6, 6, 5, 7]]


In [ ]:

# compara si hay un elemento mayor al numero dado
import numpy as np

array= np.random.randint(1,100 , size=(3,3))
print(array)
print(np.any(array > 10))

# busca un numero dado en el array
numero = 4
if( numero in array):
    print("si hay un 4")
else:
    print("no hay un 4")

#dividir un array
split_array = np.split(array,3)
print(split_array)

[[92 81 35]
 [52  9 78]
 [20 35 29]]
True
no hay un 4
[array([[92, 81, 35]]), array([[52,  9, 78]]), array([[20, 35, 29]])]


In [ ]:
import numpy as np

precios = np.random.randint(100,1000, size=(3,3))
descuentos = np.array([10,20,30])
print(precios)

resultado = (precios + descuentos)

print(resultado)

[[864 950 347]
 [248 654 472]
 [168 900 821]]
[[874 970 377]
 [258 674 502]
 [178 920 851]]


In [ ]:
#sacar el % de un valor
import numpy as np

# Matriz de precios
precios = np.random.randint(100, 1000, size=(3, 3))
# Ajustar descuentos para que tenga 3 elementos
descuentos = np.array([10, 20, 30])

print("Precios:\n", precios)

# Aplicar descuentos
resultado = np.divide(precios, descuentos[:, None]) * 100  # Ajustar dimensiones para broadcasting

print("Resultado:\n", resultado)


Precios:
 [[574 512 673]
 [525 178 902]
 [854 720 427]]
Resultado:
 [[5740.         5120.         6730.        ]
 [2625.          890.         4510.        ]
 [2846.66666667 2400.         1423.33333333]]


In [ ]:
# dividir un array
import numpy as np

array_a = np.random.randint(1,20, size=(4,20))
array_b = np.split(array_a,4)

print(array_a)
print(array_b)

[[19 11 16  7 15  1  3  4  1  8  1 19 14 18 11  2 19  4 17 18]
 [ 2  4 10 14  4 18  6  7 15  7  4  5  1  9 13 16  6 13  4 10]
 [10 12 10  7  8  8 13  9 19  8 12  4 18 10 14 18  4 19  4 17]
 [16  2  3 16  8 17 11 19  6  1  6 18  8 16  3  7 19  6  4 12]]
[array([[19, 11, 16,  7, 15,  1,  3,  4,  1,  8,  1, 19, 14, 18, 11,  2,
        19,  4, 17, 18]]), array([[ 2,  4, 10, 14,  4, 18,  6,  7, 15,  7,  4,  5,  1,  9, 13, 16,
         6, 13,  4, 10]]), array([[10, 12, 10,  7,  8,  8, 13,  9, 19,  8, 12,  4, 18, 10, 14, 18,
         4, 19,  4, 17]]), array([[16,  2,  3, 16,  8, 17, 11, 19,  6,  1,  6, 18,  8, 16,  3,  7,
        19,  6,  4, 12]])]


In [ ]:
# contar resultados de un array

survey_responses = np.array(["bueno", "excelente", "malo", "bueno", "bueno", "malo", "malo", "bueno", "excelente", "malo"])

conteo, counts = np.unique(survey_responses , return_counts=True) # cuenta las veces que esta un valor en el array
print("Valores únicos:",conteo )
print(counts )



Valores únicos: ['bueno' 'excelente' 'malo']
[4 2 4]


In [ ]:
import numpy as np

array = np.random.randint(1,10, size=(3,3))
print(array)
print("//////////////////////////////")
trasnpuesta = array.T
print(trasnpuesta)

[[5 1 2]
 [3 5 9]
 [4 8 3]]
//////////////////////////////
[[5 3 4]
 [1 5 8]
 [2 9 3]]


In [ ]:
import numpy as np

array = np.random.randint(1,10,size=(15))
print(array)

print(array.size) # cuenta los elementos del array

print("//////////////////////////////")

print(array.reshape(3,5))

print("//////////////////////////////")

print(np.flip(array)) # invierte el array


[6 7 2 7 1 6 8 6 1 6 5 6 9 5 2]
15
//////////////////////////////
[[6 7 2 7 1]
 [6 8 6 1 6]
 [5 6 9 5 2]]
//////////////////////////////
[2 5 9 6 5 6 1 6 8 6 1 7 2 7 6]


**ejercicios practicos:**


In [ ]:
#Instrucción: Crea dos arrays de 1D con valores enteros y realiza las operaciones de suma, resta, multiplicación, y división entre ellos.

import numpy as np

array_1 = np.array([1,2,3,4,5])
array_2 = np.array([6,7,8,9,10])

suma = array_1 + array_2
resta = array_2- array_1
multiplicacion = array_1 * array_2
division = array_2 / array_1

print('suma',suma)
print("resta",resta)
print("mutiplicacion",multiplicacion)
print("division",division)

suma [ 7  9 11 13 15]
resta [5 5 5 5 5]
mutiplicacion [ 6 14 24 36 50]
division [6.         3.5        2.66666667 2.25       2.        ]


In [ ]:
# Instrucción: Dado un array de datos, calcula la media, mediana, varianza, y desviación estándar.
import numpy as np

datos = np.array([23, 76, 35, 67, 89, 45, 68, 79, 35])
media = np.mean(datos)
mediana = np.median(datos)
varianza = np.var(datos)
desviasion = np.std(datos)

print('media',media)
print("mediana",mediana)
print("varianza",varianza)
print("desviacion",desviasion)



media 57.44444444444444
mediana 67.0
varianza 484.02469135802465
desviacion 22.000561160071
[23 35 35 45 67 68 76 79 89]


In [ ]:
# Instrucción: Crea dos matrices de 2x2 y realiza las operaciones de suma, resta, multiplicación (producto matricial)
# y cálculo de la inversa de una de ellas.

import numpy as np

matriz_1 = np.array([[4,7],[2,6]])
matriz_2 = np.array([[5,6],[7,8]])

suma = matriz_1 + matriz_2
resta = matriz_2 - matriz_1
multiplicacion = np.dot(matriz_1,matriz_2)
inversa = np.linalg.inv(matriz_1)
# Verificación de la inversa
verificacion = np.dot(matriz_1, inversa)

print('suma',suma)
print("resta",resta)
print("mutiplicacion",multiplicacion)
print("inversa",inversa)


suma [[ 9 13]
 [ 9 14]]
resta [[ 1 -1]
 [ 5  2]]
mutiplicacion [[69 80]
 [52 60]]
inversa [[ 0.6 -0.7]
 [-0.2  0.4]]


In [ ]:
#Resolución de un Sistema de Ecuaciones Lineales

#Instrucción: Resuelve el sistema de ecuaciones lineales dado por Ax=b, donde A es una matriz 2x2 y b es un vector de 2 elementos.

#Ax=bAx = b


import numpy as np

A = np.array([[3, 2], [1, 4]])
b = np.array([1, 2])

x = np.linalg.solve(A, b)

print(x)

[0.  0.5]


In [ ]:

#Instrucción: Genera un array de 1000 números aleatorios que sigan una distribución normal con media 0 y desviación estándar 1.
# Calcula la media y desviación estándar del array generado.

import numpy  as np

array = np.random.normal(0,1,100)

print(array)
media_simulada = np.mean(array)
desviacion_simulada = np.std(array)

print("Media de los datos simulados:", media_simulada)
print("Desviación estándar de los datos simulados:", desviacion_simulada)


[ 0.62618297 -1.37499746 -1.45041254 -0.17407766  0.67259711  0.00989574
 -0.92964053 -0.18671593  2.60423719 -0.72255091 -0.30398234 -0.0558324
  0.39659566 -0.12921284  1.45023327 -0.59185587  1.10258987  1.14579197
  0.00644364  1.38409996 -1.80175888 -0.29420963  0.59013427  0.58372122
  1.05429737  0.89584236 -1.64916014 -0.97767973  1.01141122  0.94887864
  1.34093236 -1.52096274  0.08145613 -0.22858573 -0.29268468 -0.32362348
  1.30772657  0.96426774  0.67706359 -2.15380632  0.48927956  0.20187645
 -0.0684983  -2.11002117  2.00783996 -0.63309169  0.22730212  0.46133022
  0.14809973 -1.08788646  0.55929359 -1.48072735  2.33286149 -0.56590036
 -1.5033704  -0.56383983 -0.42879912 -0.03432809 -0.00284483  0.47793014
  1.28724139  1.16418647  1.34100492  0.62605983  0.71868625  0.76779955
  1.88267682 -0.17260977 -1.25365355 -0.38557503 -0.95357147  2.75781336
  0.9786665  -0.52858311  1.24867714  1.71990797 -1.5874606  -1.96669279
 -0.76714013  1.55013379  0.2666346  -0.47908481 -0.

# Nueva sección